function [prtLookup] = buildPRT()
    prtLookup{1,1} = 'AVLocal';
        prtLookup{1,2} = 'AVSpeech';
    prtLookup{2,1} = 'Bio-Motion';
        prtLookup{2,2} = 'BioLocalizer';
    prtLookup{3,1} = 'ComboLocal';
        prtLookup{3,2} = 'FFALO*FIXED';
    prtLookup{4,1} = 'DynamicFaces';
        prtLookup{4,2} = 'DynamicFaces';
    prtLookup{5,1} = 'MTLocal';
        prtLookup{5,2} = 'OpticFlowCenter';
    prtLookup{6,1} = 'SocialLocal';
        prtLookup{6,2} = 'sociallocal';
    prtLookup{7,1} = 'Speech';
        prtLookup{7,2} = 'SpeechLocal';
    prtLookup{8,1} = 'ToM';
        prtLookup{8,2} = 'ToMloc';
    prtLookup{9,1} = 'BowtieRetino';
        prtLookup{9,2} = [];
end